name: Ruby

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        ruby: [ jruby-head ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JRuby versions
      uses: ruby/setup-ruby-pkgs@master
      with:
        ruby-version: ${{ matrix.ruby }}
        mingw: _upgrade_
    - name: Build and test with rake
      run: |
        ruby extconf.rb
        make
        gem install rspec
        rake spec
